language: android
jdk: oraclejdk8
env:
  matrix:
  - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
android:
  components:
  - build-tools-20.0
before_script:
- cp keystore.properties.example keystore.properties
- cp readability.properties.example readability.properties
- cp local.properties.example local.properties
script: "./gradlew clean assembleDebug"
deploy:
  provider: releases
  api_key:
    secure: IzDuRCD8EEZ6LFe8xzBnp1roZ6tx5gC8pLtJZQ6FpdRF1L6gOEB/4o1ruPwVJBb3iz3TlYhMvrEmZo2oAkFOE6o1fzKpjMCl+olHxA1CGVBWQKBEm9CLpH73+/GVeFjg+jUyCsvumFJ/8OG12cxiIq3KPglm71nbWKavqxUGO78=
  file: "app/build/outputs/apk/app-release.apk"
  on:
    repo: dinosaurwithakatana/holo_hacker_news
    branch: master
    tags: true
    all_branches: true
